### ISSUE TITLE
bodyParser is no longer bundled with Express impacting fbgraphapi Usage example 

### ISSUE THREAD

**Issue by dre32722** [vanng822/facebook-nodejs#10]
I'm brand new to node and facebook api's - just tried fbgraphapi install and get the following error when running the Usage example code with my App Id and Token. 

C:\Users\dreid\s2v-node\node_modules\express\lib\express.js:99
      throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
      ^

Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (C:\Users\dreid\s2v-node\node_modules\express\lib\express.js:99:13)
    at Object.<anonymous> (C:\Users\dreid\s2v-node\node_modules\fbgraphapi\test\test-with-access-token.js:12:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\dreid\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\dreid\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\Users\dreid\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (C:\Users\dreid\AppData\Roaming\npm\node_modules\mocha\bin_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by vanng822** [comment]
Thanks for reporting @dre32722 

I will take a look when I have some time. If you have time can you check the latest and create an example and PR?

**Comment by vanng822** [comment]
Just updated example, please try it out. Thank you
